<a href="https://colab.research.google.com/github/surajkrpirari2007/surajkasdj/blob/main/titanic_pred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as mlt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')
data=sns.load_dataset("titanic")

data['embark_town'].value_counts()
data['class'].value_counts()
data['deck'].value_counts()
data['deck'].fillna(data['deck'].mode()[0],inplace=True)
data['embark_town'].fillna(data['embark_town'].mode()[0],inplace=True)
data['age'].fillna(data['age'].mean(),inplace=True)
data.drop(columns='who',inplace=True)

data['pclass'].value_counts()
data.drop(columns=['class','alive','sex','embarked'],inplace=True)
data['embark_town']=data['embark_town'].map({
    'Southampton':0,
    'Cherbourg':1,
    'Queenstown':2
})

data['deck']=data['deck'].map({
    'A':0,
    'B':1,
    'C':2,
    'D':3,
    'E':4,
    'F':5,
    'G':6
})
data['adult_male']=data['adult_male'].map({
    True:1,
    False:0
})
data['alone']=data['alone'].map({
    True:1,
    False:0
})

display(data)
data.info()

,survived,pclass,age,sibsp,parch,fare,adult_male,deck,embark_town,alone
0,0,3,22.000000,1,0,7.2500,1,2,0,0
1,1,1,38.000000,1,0,71.2833,0,2,1,0
2,1,3,26.000000,0,0,7.9250,0,2,0,1
3,1,1,35.000000,1,0,53.1000,0,2,0,0
4,0,3,35.000000,0,0,8.0500,1,2,0,1
...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.000000,0,0,13.0000,1,2,0,1
887,1,1,19.000000,0,0,30.0000,0,1,0,1
888,0,3,29.699118,1,2,23.4500,0,2,0,0
889,1,1,26.000000,0,0,30.0000,1,2,1,1
890,0,3,32.000000,0,0,7.7500,1,2,2,1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   age          891 non-null    float64
 3   sibsp        891 non-null    int64
 4   parch        891 non-null    int64
 5   fare         891 non-null    float64
 6   adult_male   891 non-null    int64
 7   deck         891 non-null    category
 8   embark_town  891 non-null    int64
 9   alone        891 non-null    int64
dtypes: category(1), float64(2), int64(7)
memory usage: 64.0 KB

In [40]:
x=data.drop(columns="survived")
y=data['survived']

In [41]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
list_col=x.columns
x[list_col]=sc.fit_transform(x[list_col])

x

,pclass,age,sibsp,parch,fare,adult_male,deck,embark_town,alone
0,0.827377,-0.592481,0.432793,-0.473674,-0.502445,0.811922,-0.119419,-0.568837,-1.231645
1,-1.566107,0.638789,0.432793,-0.473674,0.786845,-1.231645,-0.119419,1.005181,-1.231645
2,0.827377,-0.284663,-0.474545,-0.473674,-0.488854,-1.231645,-0.119419,-0.568837,0.811922
3,-1.566107,0.407926,0.432793,-0.473674,0.420730,-1.231645,-0.119419,-0.568837,-1.231645
4,0.827377,0.407926,-0.474545,-0.473674,-0.486337,0.811922,-0.119419,-0.568837,0.811922
...,...,...,...,...,...,...,...,...,...
886,-0.369365,-0.207709,-0.474545,-0.473674,-0.386671,0.811922,-0.119419,-0.568837,0.811922
887,-1.566107,-0.823344,-0.474545,-0.473674,-0.044381,-1.231645,-1.538119,-0.568837,0.811922
888,0.827377,0.000000,0.432793,2.008933,-0.176263,-1.231645,-0.119419,-0.568837,-1.231645
889,-1.566107,-0.284663,-0.474545,-0.473674,-0.044381,0.811922,-0.119419,1.005181,0.811922
890,0.827377,0.177063,-0.474545,-0.473674,-0.492378,0.811922,-0.119419,2.579199,0.811922

In [44]:
from numpy.random import rand
from sklearn.model_selection import cross_val_score,GridSearchCV,RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
val_sc=cross_val_score(lr,x,y,cv=5)
print(val_sc.mean())

0.819295712761283

In [50]:
grid_s_cv=GridSearchCV((lr),{
    "penalty":['l1', 'l2', 'elasticnet',None],
    "C":[1,2,3]
},cv=5,)
grid_s_cv.fit(x,y)
result=pd.DataFrame(grid_s_cv.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_penalty,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001381,0.000475,0.000000,0.000000,1,l1,"{'C': 1, 'penalty': 'l1'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
1,0.006576,0.000261,0.003329,0.000399,1,l2,"{'C': 1, 'penalty': 'l2'}",0.826816,0.803371,0.797753,0.808989,0.859551,0.819296,0.022365,1
2,0.001575,0.000103,0.000000,0.000000,1,elasticnet,"{'C': 1, 'penalty': 'elasticnet'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
3,0.001472,0.000042,0.000000,0.000000,2,l1,"{'C': 2, 'penalty': 'l1'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4,0.006694,0.000534,0.003026,0.000120,2,l2,"{'C': 2, 'penalty': 'l2'}",0.826816,0.797753,0.797753,0.808989,0.859551,0.818172,0.023260,2
5,0.001686,0.000043,0.000000,0.000000,2,elasticnet,"{'C': 2, 'penalty': 'elasticnet'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
6,0.001620,0.000033,0.000000,0.000000,3,l1,"{'C': 3, 'penalty': 'l1'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
7,0.007323,0.000166,0.003295,0.000025,3,l2,"{'C': 3, 'penalty': 'l2'}",0.826816,0.797753,0.797753,0.808989,0.859551,0.818172,0.023260,2
8,0.001714,0.000021,0.000000,0.000000,3,elasticnet,"{'C': 3, 'penalty': 'elasticnet'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,4

In [53]:
from sklearn.ensemble import StackingClassifier
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
base_model=[
    ("svm",SVC()),
    ('knn',KNeighborsClassifier()),
    ('dt',DecisionTreeClassifier())
]
meta_model=LogisticRegression()
stacking_model=StackingClassifier(
    estimators=base_model,
    final_estimator=meta_model
)
stacking_model.fit(x_train,y_train)

StackingClassifier(estimators=[('svm', SVC()), ('knn', KNeighborsClassifier()),
                               ('dt', DecisionTreeClassifier())],
                   final_estimator=LogisticRegression())

In [54]:
pred=stacking_model.predict(x_test)
display(pred[:10])
display(y_test.head(10))
accu_sc=accuracy_score(y_test,pred)
con_mat=confusion_matrix(y_test,pred)
class_rep=classification_report(y_test,pred)
print(accu_sc,"\n",con_mat,"\n",class_rep)

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1])

709    1
439    0
840    0
720    1
39     1
290    1
300    1
333    0
208    1
136    1
Name: survived, dtype: int64

0.8268156424581006
 [[93 12]
 [19 55]]
               precision    recall  f1-score   support

           0       0.83      0.89      0.86       105
           1       0.82      0.74      0.78        74

    accuracy                           0.83       179
   macro avg       0.83      0.81      0.82       179
weighted avg       0.83      0.83      0.83       179

In [59]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(
    n_estimators=100,
    criterion='gini',
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
)
rf.fit(x_train,y_train)

RandomForestClassifier()

In [58]:
rf_pred=rf.predict(x_test)
display(rf_pred[:10])
display(y_test.head(10))
acc_sc_rf=accuracy_score(y_test,rf_pred)
con_mat_rf=confusion_matrix(y_test,rf_pred)
class_rep_rf=classification_report(y_test,rf_pred)
print(acc_sc_rf,"\n",con_mat_rf,"\n",class_rep_rf)

array([0, 0, 0, 1, 0, 1, 1, 0, 1, 1])

709    1
439    0
840    0
720    1
39     1
290    1
300    1
333    0
208    1
136    1
Name: survived, dtype: int64

0.8044692737430168
 [[90 15]
 [20 54]]
               precision    recall  f1-score   support

           0       0.82      0.86      0.84       105
           1       0.78      0.73      0.76        74

    accuracy                           0.80       179
   macro avg       0.80      0.79      0.80       179
weighted avg       0.80      0.80      0.80       179

In [60]:
from sklearn.ensemble import AdaBoostClassifier
ada=AdaBoostClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)
ada.fit(x_train,y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(), learning_rate=0.1,
                   n_estimators=100, random_state=42)

In [61]:
pred_ada=ada.predict(x_test)
display(pred_ada[:10])
display(y_test.head(10))
acc_sc_ada=accuracy_score(y_test,pred_ada)
con_mat_ada=confusion_matrix(y_test,pred_ada)
class_rep_ada=classification_report(y_test,pred_ada)
print(acc_sc_ada,"\n",con_mat_ada,"\n",class_rep_ada)

array([0, 0, 0, 1, 1, 1, 1, 0, 0, 1])

709    1
439    0
840    0
720    1
39     1
290    1
300    1
333    0
208    1
136    1
Name: survived, dtype: int64

0.776536312849162
 [[87 18]
 [22 52]]
               precision    recall  f1-score   support

           0       0.80      0.83      0.81       105
           1       0.74      0.70      0.72        74

    accuracy                           0.78       179
   macro avg       0.77      0.77      0.77       179
weighted avg       0.78      0.78      0.78       179

In [64]:
from sklearn.ensemble import GradientBoostingClassifier
gb=GradientBoostingClassifier(

    n_estimators=100,
    learning_rate=0.1,
    random_state=42
)
gb.fit(x_train,y_train)

GradientBoostingClassifier(random_state=42)

In [65]:
pred_gb=gb.predict(x_test)
display(pred_gb[:10])
display(y_test.head(10))
acc_sc_gb=accuracy_score(y_test,pred_gb)
con_mat_gb=confusion_matrix(y_test,pred_gb)
class_rep_gb=classification_report(y_test,pred_gb)
print(acc_sc_gb,"\n",con_mat_gb,"\n",class_rep_gb)

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1])

709    1
439    0
840    0
720    1
39     1
290    1
300    1
333    0
208    1
136    1
Name: survived, dtype: int64

0.8100558659217877
 [[90 15]
 [19 55]]
               precision    recall  f1-score   support

           0       0.83      0.86      0.84       105
           1       0.79      0.74      0.76        74

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179

In [67]:
import xgboost as xgb
xgb_model=xgb.XGBClassifier(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=5,
    min_child_weight=3,
    subsample=0.8,
    colsample_bytree=0.8,
    gamma=0.1,
    random_state=42
)
xgb_model.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=0.1, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=3, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=200,
              n_jobs=None, num_parallel_tree=None, ...)

In [68]:
pred_xgb=xgb_model.predict(x_test)
display(pred_xgb[:10])
display(y_test.head(10))
acc_sc_xgb=accuracy_score(y_test,pred_xgb)
con_mat_xgb=confusion_matrix(y_test,pred_xgb)
class_rep_xgb=classification_report(y_test,pred_xgb)
print(acc_sc_xgb,"\n",con_mat_xgb,"\n",class_rep_xgb)

array([0, 0, 0, 1, 1, 1, 1, 0, 1, 1])

709    1
439    0
840    0
720    1
39     1
290    1
300    1
333    0
208    1
136    1
Name: survived, dtype: int64

0.8268156424581006
 [[92 13]
 [18 56]]
               precision    recall  f1-score   support

           0       0.84      0.88      0.86       105
           1       0.81      0.76      0.78        74

    accuracy                           0.83       179
   macro avg       0.82      0.82      0.82       179
weighted avg       0.83      0.83      0.83       179